/*
TRIGGER: AUDITORIA DE MUDANÇAS NO NÍVEL DE DEGRADAÇÃO DO SOLO

Função: Registra mudanças no nível de degradação e gera alertas de piora

Características:
Tabela de auditoria criada automaticamente
Log completo de mudanças com usuário e timestamp
Alerta automático se degradação piorar 2+ níveis
Rastreabilidade total das alterações

*/

-- Primeiro, criar tabela de auditoria
/* Ja criada!
CREATE TABLE GS_WW_AUDITORIA_DEGRADACAO (
    id_auditoria        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_propriedade      NUMBER NOT NULL,
    nivel_anterior      NUMBER(1),
    nivel_novo          NUMBER(1),
    data_mudanca        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario_alteracao   VARCHAR2(50) DEFAULT USER,
    observacoes         VARCHAR2(500)
);
*/

CREATE OR REPLACE TRIGGER TRG_AUDITORIA_DEGRADACAO_SOLO
    AFTER UPDATE OF id_nivel_degradacao ON GS_WW_PROPRIEDADE_RURAL
    FOR EACH ROW
DECLARE
    v_nome_propriedade    GS_WW_PROPRIEDADE_RURAL.nome_propriedade%TYPE;
    v_nome_produtor       GS_WW_PRODUTOR_RURAL.nome_completo%TYPE;
    v_descricao_anterior  GS_WW_NIVEL_DEGRADACAO_SOLO.descricao_degradacao%TYPE;
    v_descricao_nova      GS_WW_NIVEL_DEGRADACAO_SOLO.descricao_degradacao%TYPE;
    v_observacoes         VARCHAR2(500);
    v_nivel_severidade    NUMBER(1);
BEGIN
    -- Só executar se realmente houve mudança no nível
    IF :OLD.id_nivel_degradacao != :NEW.id_nivel_degradacao THEN
        
        -- Buscar informações da propriedade e produtor
        SELECT pr.nome_propriedade, prod.nome_completo
        INTO v_nome_propriedade, v_nome_produtor
        FROM GS_WW_PROPRIEDADE_RURAL pr
        JOIN GS_WW_PRODUTOR_RURAL prod ON pr.id_produtor = prod.id_produtor
        WHERE pr.id_propriedade = :NEW.id_propriedade;
        
        -- Buscar descrições dos níveis
        SELECT descricao_degradacao INTO v_descricao_anterior
        FROM GS_WW_NIVEL_DEGRADACAO_SOLO 
        WHERE id_nivel_degradacao = :OLD.id_nivel_degradacao;
        
        SELECT descricao_degradacao INTO v_descricao_nova
        FROM GS_WW_NIVEL_DEGRADACAO_SOLO 
        WHERE id_nivel_degradacao = :NEW.id_nivel_degradacao;
        
        -- Preparar observações
        v_observacoes := 'Propriedade: ' || v_nome_propriedade || 
                        ' | Produtor: ' || v_nome_produtor ||
                        ' | De: ' || v_descricao_anterior ||
                        ' | Para: ' || v_descricao_nova;
        
        -- Inserir registro de auditoria
        INSERT INTO GS_WW_AUDITORIA_DEGRADACAO (
            id_propriedade,
            nivel_anterior,
            nivel_novo,
            observacoes
        ) VALUES (
            :NEW.id_propriedade,
            :OLD.id_nivel_degradacao,
            :NEW.id_nivel_degradacao,
            v_observacoes
        );
        
        -- Gerar alerta se houve piora significativa (aumento de 2+ níveis)
        IF :NEW.id_nivel_degradacao > :OLD.id_nivel_degradacao + 1 THEN
            -- Determinar severidade baseada na piora
            IF :NEW.id_nivel_degradacao >= 4 THEN
                v_nivel_severidade := 4; -- CRÍTICO
            ELSE
                v_nivel_severidade := 3; -- ALTO
            END IF;
            
            -- Gerar alerta de degradação
            INSERT INTO GS_WW_ALERTA (
                id_produtor,
                id_leitura,
                id_nivel_severidade,
                timestamp_alerta,
                descricao_alerta
            ) VALUES (
                (SELECT id_produtor FROM GS_WW_PROPRIEDADE_RURAL WHERE id_propriedade = :NEW.id_propriedade),
                NULL, -- Não vinculado a uma leitura específica
                v_nivel_severidade,
                CURRENT_TIMESTAMP,
                'DEGRADAÇÃO ACELERADA: ' || v_nome_propriedade || 
                ' teve piora significativa no solo - ' || v_descricao_nova
            );
        END IF;
        
        -- Log para auditoria
        DBMS_OUTPUT.PUT_LINE('AUDITORIA: Nível de degradação alterado - ' || v_observacoes);
    END IF;
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro na auditoria de degradação: ' || SQLERRM);
END TRG_AUDITORIA_DEGRADACAO_SOLO;
/