-- ============================================================================
-- 1. INSERÇÃO NAS TABELAS DE APOIO
-- ============================================================================

-- Inserção na Tabela Tipo de Sensor
INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('Umidade Solo', 'Sensor de umidade do solo capacitivo', '%', 0, 100);

INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('Temperatura', 'Sensor de temperatura ambiente', '°C', -20, 60);

INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('Pluviômetro', 'Sensor de precipitação pluviométrica', 'mm', 0, 500);

INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('pH Solo', 'Sensor de pH do solo', 'pH', 0, 14);


-- Inserção na Tabela Nível de Severidade
INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, ACOES_RECOMENDADAS) 
VALUES ('BAIXO', 'Nível de atenção baixo', 'Monitoramento contínuo recomendado');

INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, ACOES_RECOMENDADAS) 
VALUES ('MEDIO', 'Nível de atenção médio', 'Verificação in loco e ajustes preventivos');

INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, ACOES_RECOMENDADAS) 
VALUES ('ALTO', 'Nível de atenção alto', 'Ação imediata necessária, risco de perda');

INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, ACOES_RECOMENDADAS) 
VALUES ('CRITICO', 'Nível crítico de emergência', 'Intervenção urgente, evacuação se necessário');

INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, ACOES_RECOMENDADAS) 
VALUES ('INFO', 'Informativo', 'Apenas para conhecimento, sem ação necessária');

-- Inserção na Tabela Nível de Degradação do Solo
INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, ACOES_CORRETIVAS) 
VALUES ('EXCELENTE', 'Solo em excelente estado de conservação', 1, 'Manter práticas atuais de manejo');

INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, ACOES_CORRETIVAS) 
VALUES ('BOM', 'Solo em bom estado com sinais mínimos de degradação', 2, 'Implementar rotação de culturas');

INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, ACOES_CORRETIVAS) 
VALUES ('MODERADO', 'Degradação moderada com perda de nutrientes', 3, 'Aplicar adubação orgânica e terraceamento');

INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, ACOES_CORRETIVAS) 
VALUES ('RUIM', 'Solo com degradação avançada', 4, 'Recuperação com plantio direto e cobertura vegetal');

INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, ACOES_CORRETIVAS) 
VALUES ('CRITICO', 'Solo severamente degradado', 5, 'Recuperação intensiva com pousio e revegetação');

-- ============================================================================
-- 2. INSERÇÃO NAS TABELAS PRINCIPAIS
-- ============================================================================

-- Inserção na Tabela Produtor Rural
INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE, SENHA, DATA_CADASTRO) 
VALUES ('João Silva Santos', '123.456.789-10', 'joao.silva@email.com', '(11) 98765-4321', 'joao123', SYSDATE);

INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE, SENHA, DATA_CADASTRO) 
VALUES ('Maria Oliveira Costa', '987.654.321-20', 'maria.costa@email.com', '(11) 98765-4321', 'maria456', SYSDATE);

INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE, SENHA, DATA_CADASTRO) 
VALUES ('Carlos Ferreira Lima', '456.789.123-30', 'carlos.lima@email.com', '(11) 97654-3210', 'carlos789', SYSDATE);

INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE, SENHA, DATA_CADASTRO) 
VALUES ('Ana Paula Rodrigues', '789.123.456-40', 'ana.rodrigues@email.com', '(11) 96543-2109', 'ana2024', SYSDATE);

INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE, SENHA, DATA_CADASTRO) 
VALUES ('Roberto Almeida Souza', '321.654.987-50', 'roberto.souza@email.com', '(11) 95432-1098', 'roberto321', SYSDATE);


-- Inserção na Tabela Propriedade Rural
INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, DATA_CADASTRO) 
VALUES (1, 1, 'Fazenda São João', -23.5505199, -46.6333094, 150.75, SYSDATE);

INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, DATA_CADASTRO) 
VALUES (2, 2, 'Sítio Santa Maria', -22.9068467, -43.1728965, 85.30, SYSDATE);

INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, DATA_CADASTRO) 
VALUES (3, 3, 'Estância Boa Vista', -25.4284700, -49.2733200, 220.50, SYSDATE);

INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, DATA_CADASTRO) 
VALUES (4, 2, 'Chácara Esperança', -30.0346000, -51.2177000, 45.80, SYSDATE);

INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, DATA_CADASTRO) 
VALUES (5, 4, 'Fazenda Novo Horizonte', -15.7801000, -47.9292000, 380.25, SYSDATE);

-- Inserção na Tabela Sensor IoT
INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, DATA_INSTALACAO) 
VALUES (1, 1, 'SoilWatch Pro V2.1', TO_DATE('2024-01-15', 'YYYY-MM-DD'));

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, DATA_INSTALACAO) 
VALUES (2, 2, 'TempSensor MAX-200', TO_DATE('2024-02-10', 'YYYY-MM-DD'));

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, DATA_INSTALACAO) 
VALUES (3, 3, 'RainGauge Digital X1', TO_DATE('2024-01-20', 'YYYY-MM-DD'));

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, DATA_INSTALACAO) 
VALUES (4, 1, 'SoilMoisture Elite', TO_DATE('2024-03-05', 'YYYY-MM-DD'));

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, DATA_INSTALACAO) 
VALUES (5, 4, 'pH-Meter AgriTech', TO_DATE('2024-02-28', 'YYYY-MM-DD'));

-- Inserção na Tabela Leitura Sensor
INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, TIMESTAMP_LEITURA, UMIDADE_SOLO, TEMPERATURA_AR, PRECIPITACAO_MM) 
VALUES (1, TIMESTAMP '2024-05-30 08:00:00', 45.8, 22.5, 0.0);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, TIMESTAMP_LEITURA, UMIDADE_SOLO, TEMPERATURA_AR, PRECIPITACAO_MM) 
VALUES (2, TIMESTAMP '2024-05-30 08:15:00', 38.2, 35.8, 0.0);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, TIMESTAMP_LEITURA, UMIDADE_SOLO, TEMPERATURA_AR, PRECIPITACAO_MM) 
VALUES (3, TIMESTAMP '2024-05-30 08:30:00', 52.1, 18.3, 12.5);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, TIMESTAMP_LEITURA, UMIDADE_SOLO, TEMPERATURA_AR, PRECIPITACAO_MM) 
VALUES (4, TIMESTAMP '2024-05-30 08:45:00', 28.7, 28.9, 0.0);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, TIMESTAMP_LEITURA, UMIDADE_SOLO, TEMPERATURA_AR, PRECIPITACAO_MM) 
VALUES (5, TIMESTAMP '2024-05-30 09:00:00', 41.3, 24.2, 2.8);

-- Inserção na Tabela Alerta
INSERT INTO GS_WW_ALERTA (ID_PRODUTOR, ID_LEITURA, ID_NIVEL_SEVERIDADE, TIMESTAMP_ALERTA, DESCRICAO_ALERTA) 
VALUES (1, 1, 2, TIMESTAMP '2024-05-30 08:05:00', 'Umidade do solo abaixo do recomendado para a cultura');

INSERT INTO GS_WW_ALERTA (ID_PRODUTOR, ID_LEITURA, ID_NIVEL_SEVERIDADE, TIMESTAMP_ALERTA, DESCRICAO_ALERTA) 
VALUES (2, 2, 3, TIMESTAMP '2024-05-30 08:20:00', 'Temperatura elevada detectada - risco de estresse térmico');

INSERT INTO GS_WW_ALERTA (ID_PRODUTOR, ID_LEITURA, ID_NIVEL_SEVERIDADE, TIMESTAMP_ALERTA, DESCRICAO_ALERTA) 
VALUES (3, 3, 1, TIMESTAMP '2024-05-30 08:35:00', 'Precipitação moderada registrada - condições favoráveis');

INSERT INTO GS_WW_ALERTA (ID_PRODUTOR, ID_LEITURA, ID_NIVEL_SEVERIDADE, TIMESTAMP_ALERTA, DESCRICAO_ALERTA) 
VALUES (4, 4, 4, TIMESTAMP '2024-05-30 08:50:00', 'Umidade crítica - irrigação urgente necessária');

INSERT INTO GS_WW_ALERTA (ID_PRODUTOR, ID_LEITURA, ID_NIVEL_SEVERIDADE, TIMESTAMP_ALERTA, DESCRICAO_ALERTA) 
VALUES (5, 5, 2, TIMESTAMP '2024-05-30 09:05:00', 'Condições climáticas instáveis - monitoramento reforçado');

